#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Plot charts from prototype_stats.csv generated by analyze_retrieved_data.py.

Expected columns in prototype_stats.csv:
- prototype_id
- task_type
- count
- share
- score_mean
- score_median
- score_p10
- score_p90
- assistant_chars_mean
- total_chars_mean
- has_tools_rate
- malformed_rate
- dup_norm_rate
- sources
- buckets

Usage:
python plot_prototype_stats.py \
  --input prototype_stats.csv \
  --output-dir prototype_plots \
  --topn 30

Outputs:
- top_prototypes_by_count.png
- top_prototypes_by_share.png
- prototype_count_distribution.png
- prototype_score_mean_distribution.png
- prototype_malformed_rate_distribution.png
- prototype_dup_rate_distribution.png
- plot_summary.json
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import List

import matplotlib.pyplot as plt
import pandas as pd


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Plot charts from prototype_stats.csv")
    p.add_argument("--input", required=True, help="Path to prototype_stats.csv")
    p.add_argument("--output-dir", required=True, help="Directory to save output charts")
    p.add_argument("--topn", type=int, default=30, help="Top N prototypes to show in bar charts")
    p.add_argument("--min-count", type=int, default=1, help="Optional minimum count filter before plotting")
    p.add_argument("--dpi", type=int, default=180, help="Output image DPI")
    return p.parse_args()


def require_columns(df: pd.DataFrame, cols: List[str]) -> None:
    missing = [c for c in cols if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns: {missing}")


def save_barh(df: pd.DataFrame, label_col: str, value_col: str, title: str, xlabel: str, out_path: Path, topn: int, dpi: int) -> None:
    sub = df.sort_values(value_col, ascending=False).head(topn).copy()
    if sub.empty:
        return
    sub = sub.iloc[::-1]
    fig = plt.figure(figsize=(12, max(6, min(16, 0.35 * len(sub) + 2))))
    ax = fig.add_subplot(111)
    ax.barh(sub[label_col], sub[value_col])
    ax.set_title(title)
    ax.set_xlabel(xlabel)
    ax.set_ylabel(label_col)
    fig.tight_layout()
    fig.savefig(out_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


def save_hist(series: pd.Series, title: str, xlabel: str, out_path: Path, bins: int, dpi: int) -> None:
    series = pd.to_numeric(series, errors="coerce").dropna()
    if series.empty:
        return
    fig = plt.figure(figsize=(10, 6))
    ax = fig.add_subplot(111)
    ax.hist(series, bins=bins)
    ax.set_title(title)
    ax.set_xlabel(xlabel)
    ax.set_ylabel("Frequency")
    fig.tight_layout()
    fig.savefig(out_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


def main() -> None:
    args = parse_args()
    input_path = Path(args.input)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(input_path)
    require_columns(df, ["prototype_id", "count"])

    for col in [
        "count", "share", "score_mean", "score_median", "score_p10", "score_p90",
        "assistant_chars_mean", "total_chars_mean", "has_tools_rate",
        "malformed_rate", "dup_norm_rate"
    ]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    if args.min_count > 1 and "count" in df.columns:
        df = df[df["count"] >= args.min_count].copy()

    if df.empty:
        raise ValueError("No rows left after filtering. Try a smaller --min-count.")

    save_barh(
        df=df,
        label_col="prototype_id",
        value_col="count",
        title=f"Top {args.topn} Prototypes by Count",
        xlabel="Count",
        out_path=output_dir / "top_prototypes_by_count.png",
        topn=args.topn,
        dpi=args.dpi,
    )

    if "share" in df.columns:
        save_barh(
            df=df,
            label_col="prototype_id",
            value_col="share",
            title=f"Top {args.topn} Prototypes by Share",
            xlabel="Share",
            out_path=output_dir / "top_prototypes_by_share.png",
            topn=args.topn,
            dpi=args.dpi,
        )

    save_hist(
        series=df["count"],
        title="Distribution of Prototype Counts",
        xlabel="Count",
        out_path=output_dir / "prototype_count_distribution.png",
        bins=30,
        dpi=args.dpi,
    )

    if "score_mean" in df.columns:
        save_hist(
            series=df["score_mean"],
            title="Distribution of Prototype Score Mean",
            xlabel="score_mean",
            out_path=output_dir / "prototype_score_mean_distribution.png",
            bins=30,
            dpi=args.dpi,
        )

    if "malformed_rate" in df.columns:
        save_hist(
            series=df["malformed_rate"],
            title="Distribution of Prototype Malformed Rate",
            xlabel="malformed_rate",
            out_path=output_dir / "prototype_malformed_rate_distribution.png",
            bins=30,
            dpi=args.dpi,
        )

    if "dup_norm_rate" in df.columns:
        save_hist(
            series=df["dup_norm_rate"],
            title="Distribution of Prototype Normalized Duplicate Rate",
            xlabel="dup_norm_rate",
            out_path=output_dir / "prototype_dup_rate_distribution.png",
            bins=30,
            dpi=args.dpi,
        )

    summary = {
        "input": str(input_path),
        "output_dir": str(output_dir),
        "rows_after_filter": int(len(df)),
        "topn": int(args.topn),
        "min_count": int(args.min_count),
        "charts": [
            "top_prototypes_by_count.png",
            "top_prototypes_by_share.png" if "share" in df.columns else None,
            "prototype_count_distribution.png",
            "prototype_score_mean_distribution.png" if "score_mean" in df.columns else None,
            "prototype_malformed_rate_distribution.png" if "malformed_rate" in df.columns else None,
            "prototype_dup_rate_distribution.png" if "dup_norm_rate" in df.columns else None,
        ],
        "count_stats": {
            "min": float(df["count"].min()),
            "max": float(df["count"].max()),
            "mean": float(df["count"].mean()),
            "median": float(df["count"].median()),
        },
    }
    summary["charts"] = [x for x in summary["charts"] if x is not None]
    (output_dir / "plot_summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
